### ISSUE TITLE
ShowHealthStamina not working

### ISSUE THREAD

**Issue by mmiinnaa11** [OoLunar/LethalCompanyPatched#5]
![image](https://github.com/user-attachments/assets/708ba803-d57a-48be-91d0-fde55396ee5c)
![image](https://github.com/user-attachments/assets/d2a4681c-58cb-4051-a89d-c5060fc05303)

**Comment by OoLunar** [comment]
Does it show when the `x` box is unmarked? I remember it was being weird with booleans before. You'll have to reload the round after unticking it.

**Comment by mmiinnaa11** [comment]
Restarting the round/game does nothing, tried it when it's ticked and when it's unticked and it doesn't work, I tried it without mods to see if it's a mod incompat but it's not

**Comment by OoLunar** [comment]
Thanks for reporting, I'll take a look into it within the next 3-4 days

**Comment by NakiriFox** [comment]
The same issue, but using An0n_Patches doesn‘t have this problem.

**Comment by OoLunar** [comment]
I just published a new release: `1.2.1`. On my machine, the HUD correctly turns on and off through LethalConfig. Could you please download and confirm for me? Thank y'all <3
